spring:
  data:
    mongodb:
      username: nikusha
      password: nikusha123
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin

server:
  port:8088
